import type { Perspective, Sentido } from "@prisma/client";

export type BscObjectiveSeed = {
  id: string;
  perspective: Perspective;
  objective: string;
  kpiName: string;
  unit: string;
  targetValue: number;
  sentido: Sentido;
  frequency: string;
  responsible: string;
  justification: string | null;
  priorityInitiative: string | null;
  order: number;
};

export const BSC_OBJECTIVES: BscObjectiveSeed[] = [
  {
    id: "F1",
    perspective: "FINANCIERA",
    objective: "Lograr crecimiento comercial sostenible",
    kpiName: "Crecimiento de ingresos acumulados vs. año anterior",
    unit: "%",
    targetValue: 25,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Gerencia General",
    justification: "Consolidar el segundo año con expansión controlada y evidencia de tracción comercial.",
    priorityInitiative: null,
    order: 0,
  },
  {
    id: "F2",
    perspective: "FINANCIERA",
    objective: "Mejorar la rentabilidad de los proyectos",
    kpiName: "Margen bruto promedio de proyectos",
    unit: "%",
    targetValue: 35,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Gerencia General",
    justification: "Proteger margen mediante costeo, control de HH, alcance y proveedores.",
    priorityInitiative: null,
    order: 1,
  },
  {
    id: "F3",
    perspective: "FINANCIERA",
    objective: "Reducir concentración de ingresos",
    kpiName: "Participación del cliente principal en ingresos",
    unit: "%",
    targetValue: 30,
    sentido: "MENOR",
    frequency: "Trimestral",
    responsible: "Gerencia General",
    justification: "Disminuir dependencia de un solo mandante y diversificar cartera.",
    priorityInitiative: null,
    order: 2,
  },
  {
    id: "F4",
    perspective: "FINANCIERA",
    objective: "Fortalecer liquidez y cobranza",
    kpiName: "Facturas cobradas dentro de 45 días",
    unit: "%",
    targetValue: 90,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Administración",
    justification: "Asegurar caja para sostener operación y crecimiento.",
    priorityInitiative: null,
    order: 3,
  },
  {
    id: "C1",
    perspective: "CLIENTES",
    objective: "Aumentar la base de clientes activos",
    kpiName: "Clientes institucionales/empresariales activos en 12 meses",
    unit: "N°",
    targetValue: 8,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Gerencia General",
    justification: "Priorizar empresas, educación superior y colegios.",
    priorityInitiative: null,
    order: 4,
  },
  {
    id: "C2",
    perspective: "CLIENTES",
    objective: "Impulsar recurrencia y fidelización",
    kpiName: "Clientes con recompra o nuevo proyecto en 12 meses",
    unit: "%",
    targetValue: 50,
    sentido: "MAYOR",
    frequency: "Trimestral",
    responsible: "Gerencia General",
    justification: "Convertir proyectos puntuales en relaciones de mediano plazo.",
    priorityInitiative: null,
    order: 5,
  },
  {
    id: "C3",
    perspective: "CLIENTES",
    objective: "Elevar satisfacción y recomendación",
    kpiName: "NPS o índice equivalente de recomendación",
    unit: "Puntos",
    targetValue: 60,
    sentido: "MAYOR",
    frequency: "Por proyecto",
    responsible: "Calidad y Mejora Continua",
    justification: "Medir percepción al cierre y activar planes de mejora.",
    priorityInitiative: null,
    order: 6,
  },
  {
    id: "C4",
    perspective: "CLIENTES",
    objective: "Mejorar efectividad comercial",
    kpiName: "Propuestas adjudicadas / propuestas emitidas",
    unit: "%",
    targetValue: 35,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Gerencia General",
    justification: "Gestionar embudo comercial y calidad de propuestas.",
    priorityInitiative: null,
    order: 7,
  },
  {
    id: "P1",
    perspective: "PROCESOS_INTERNOS",
    objective: "Cumplir proyectos en plazo y alcance",
    kpiName: "Hitos entregados en fecha comprometida",
    unit: "%",
    targetValue: 95,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Dirección de Proyectos",
    justification: "Controlar cronograma, alcance, riesgos y dependencias.",
    priorityInitiative: null,
    order: 8,
  },
  {
    id: "P2",
    perspective: "PROCESOS_INTERNOS",
    objective: "Asegurar calidad técnica de entregables",
    kpiName: "Entregables aprobados sin retrabajo mayor",
    unit: "%",
    targetValue: 90,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Calidad y Mejora Continua",
    justification: "Operacionalizar el valor 'Rigor que transforma'.",
    priorityInitiative: null,
    order: 9,
  },
  {
    id: "P3",
    perspective: "PROCESOS_INTERNOS",
    objective: "Estandarizar el método de trabajo",
    kpiName: "Proyectos que aplican diagnóstico-diseño-implementación-evaluación-mejora",
    unit: "%",
    targetValue: 100,
    sentido: "MAYOR",
    frequency: "Trimestral",
    responsible: "Dirección de Proyectos",
    justification: "Convertir el framework institucional en estándar operativo auditable.",
    priorityInitiative: null,
    order: 10,
  },
  {
    id: "P4",
    perspective: "PROCESOS_INTERNOS",
    objective: "Acelerar respuesta comercial",
    kpiName: "Tiempo medio desde requerimiento calificado a propuesta",
    unit: "Días",
    targetValue: 5,
    sentido: "MENOR",
    frequency: "Mensual",
    responsible: "Gerencia General",
    justification: "Reducir fricción en la captación sin deteriorar pertinencia técnica.",
    priorityInitiative: null,
    order: 11,
  },
  {
    id: "A1",
    perspective: "APRENDIZAJE_CRECIMIENTO",
    objective: "Fortalecer capacidades del equipo y red",
    kpiName: "Profesionales clave con actualización anual en IA, calidad o diseño educativo",
    unit: "%",
    targetValue: 90,
    sentido: "MAYOR",
    frequency: "Semestral",
    responsible: "Calidad y Mejora Continua",
    justification: "Sostener innovación pedagógica y uso responsable de IA.",
    priorityInitiative: null,
    order: 12,
  },
  {
    id: "A2",
    perspective: "APRENDIZAJE_CRECIMIENTO",
    objective: "Construir capital de conocimiento reutilizable",
    kpiName: "Proyectos con lecciones aprendidas y activos reutilizables documentados",
    unit: "%",
    targetValue: 90,
    sentido: "MAYOR",
    frequency: "Trimestral",
    responsible: "Dirección de Proyectos",
    justification: "Evitar pérdida de conocimiento y mejorar productividad futura.",
    priorityInitiative: null,
    order: 13,
  },
  {
    id: "A3",
    perspective: "APRENDIZAJE_CRECIMIENTO",
    objective: "Desarrollar capacidad flexible de ejecución",
    kpiName: "Cobertura de perfiles críticos mediante staff/red de especialistas",
    unit: "%",
    targetValue: 100,
    sentido: "MAYOR",
    frequency: "Trimestral",
    responsible: "Gerencia General",
    justification: "Asegurar capacidad para las tres líneas de servicio y picos de demanda.",
    priorityInitiative: null,
    order: 14,
  },
  {
    id: "A4",
    perspective: "APRENDIZAJE_CRECIMIENTO",
    objective: "Instalar cultura de datos y mejora continua",
    kpiName: "Reuniones BSC realizadas con acuerdos y responsables",
    unit: "%",
    targetValue: 100,
    sentido: "MAYOR",
    frequency: "Mensual",
    responsible: "Gerencia General",
    justification: "Usar evidencia, transparencia y mejora continua como rutina de gestión.",
    priorityInitiative: null,
    order: 15,
  },
];
